version: '3.4'

services:
  minimalapi_second_tirando_da_program:
    image: minimalapisecondtirandodaprogram:dev
    container_name: "MinimalAPI_Second_Tirando_da_Program"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MinimalAPI_Second_Tirando_da_Program"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages;/.nuget/fallbackpackages2
    volumes:
      - C:\Users\glbst\Desktop\GBastos Systems\Trainning\MinimalAPI_Second_Tirando_da_Program\MinimalAPI_Trainning\MinimalAPI_Second_Tirando_da_Program:/app:rw
      - C:\Users\glbst\Desktop\GBastos Systems\Trainning\MinimalAPI_Second_Tirando_da_Program\MinimalAPI_Trainning:/src:rw
      - C:\Users\glbst\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\glbst\.nuget\packages:/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/.nuget/fallbackpackages:ro
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/.nuget/fallbackpackages2:ro
      - C:\Users\glbst\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\glbst\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\glbst\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\glbst\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net7.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages --additionalProbingPath /.nuget/fallbackpackages2  \"/app/bin/Debug/net7.0/MinimalAPI_Second_Tirando_da_Program.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true